FROM ubuntu:bionic
MAINTAINER delivery-engineering@netflix.com
RUN apt-get update && apt-get -y install openjdk-8-jre-headless wget
COPY --from=compile /compiled_sources/fiat-web/build/install/fiat /opt/fiat
RUN adduser --disabled-login --system spinnaker
USER spinnaker
CMD ["/opt/fiat/bin/fiat"]